name: Release & Publish
on:
  push:
    branches: [main, staging]
jobs:
  release:
    permissions:
      contents: write
      packages: write
    uses: BieberWorks/tooling/.github/workflows/nuget-release.yml@main
    secrets: inherit
